# 1 - Tensor *Flow*

In [17]:
import tensorflow as tf

In [18]:
tf.__version__

'2.12.0'

In [19]:
tf.config.list_physical_devices("GPU")

[]

# TensorFlow Tutorial 02 - Tensor Basics - Beginner Course

In [25]:
x = tf.constant(4)
x

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [26]:
 x = tf.constant(4, shape=(1,1), dtype = tf.float32)
 x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [33]:
# Rank - 1
x = tf.constant([1,2,3])
x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [35]:
# # Rank - 2
x = tf.constant([[1,2,3], [4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [36]:
x = tf.ones(shape=(4,4))
x

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [37]:
# Identity Matrix
x = tf.eye(3)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [38]:
# Normal Distribution
x = tf.random.normal((4,4), mean = 0, stddev = 1)
x

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.07322025,  0.23219329,  1.4598157 , -0.43702295],
       [-0.17343025, -0.95337677,  0.06181731,  0.0120345 ],
       [ 0.8640363 , -0.6843222 , -1.7089922 , -2.5420735 ],
       [-0.5191626 , -0.6658499 ,  0.03539042,  1.4967538 ]],
      dtype=float32)>

In [41]:
# Uniform Distribution
x = tf.random.uniform((3,3), minval = 0, maxval = 1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.9229038 , 0.6346358 , 0.15560925],
       [0.7806046 , 0.60513246, 0.8804239 ],
       [0.62947166, 0.7276206 , 0.88282824]], dtype=float32)>

In [43]:
# Range
x = tf.range(10)
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [45]:
# cast
x = tf.cast(x, dtype = tf.float32)
x

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [47]:
# Element Wise operations
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.add(x,y) # z = x+y also work same as add
print(z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [52]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.subtract(x,y) # z = x-y also work same as subtract
print(z)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [53]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.multiply(x,y) # z = x+y also work same as multiply
print(z)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [49]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.divide(x,y) # z = x/y also work same as devide
print(z)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [56]:
# Dot product
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.tensordot(x,y, axes = 1)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [57]:
# Dot product
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = x ** 3
print(z)

tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)


In [60]:
# Matrix Multiplication
x = tf.random.normal((3,4))
y = tf.random.normal((4,3))

z = tf.matmul(x,y) # x@y also work same as matmul
print(z)

tf.Tensor(
[[ 3.0211205   0.19429943  3.4610217 ]
 [-1.879442    0.4341002   0.40992558]
 [-0.8784565  -1.0340154  -0.50534004]], shape=(3, 3), dtype=float32)


In [61]:
# Slicing and indexing
x = tf.constant([[1,2,3,4],[5,6,7,8]])
x[0]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [62]:
x[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 5], dtype=int32)>

In [64]:
x[0,1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [66]:
# Reshaping
x = tf.random.normal((2,3))
print(x)

x = tf.reshape(x, (3,2))
print(x)

tf.Tensor(
[[-1.3184488  -1.1759168  -0.65030044]
 [-0.91957885 -0.36874563  1.0008293 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-1.3184488  -1.1759168 ]
 [-0.65030044 -0.91957885]
 [-0.36874563  1.0008293 ]], shape=(3, 2), dtype=float32)


In [70]:
x = tf.random.normal((2,3))
print(x)

x = tf.reshape(x, (6))
print('New Shape :',x)

tf.Tensor(
[[ 0.13693696  0.14962053  0.1530993 ]
 [-0.06446587  0.25939205  1.9051129 ]], shape=(2, 3), dtype=float32)
New Shape : tf.Tensor([ 0.13693696  0.14962053  0.1530993  -0.06446587  0.25939205  1.9051129 ], shape=(6,), dtype=float32)


In [71]:
# Conver tensor to numpy
x = tf.random.normal((2,3))
print(x)

x = x.numpy()
print(type(x))

tf.Tensor(
[[-0.5039079  -0.46329126  1.2222571 ]
 [ 0.02153627  0.12958081 -0.5048398 ]], shape=(2, 3), dtype=float32)
<class 'numpy.ndarray'>


In [73]:
# Numpy to Tensor
x = tf.convert_to_tensor(x)
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.5039079 , -0.46329126,  1.2222571 ],
       [ 0.02153627,  0.12958081, -0.5048398 ]], dtype=float32)>

In [74]:
# string tensor
x = tf.constant("Rawal")
print(x)

tf.Tensor(b'Rawal', shape=(), dtype=string)


In [79]:
from tensorflow.python.util.nest import yield_flat_paths
# Variable tensor
x = tf.constant([1,2,3])
print(x)

y = tf.Variable([1,2,3])
print(y)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
